### ISSUE TITLE
TypeError: can only concatenate list (not "bytes") to list

### ISSUE THREAD

**Issue by dmonad** [y-crdt/ypy-websocket#30]
On my `remove-modeldb` branch (https://github.com/dmonad/jupyterlab/tree/remove-modeldb) I get an error when running the ypy-websocket server. Since I didn't change anything related to ypy-websocket, this might affect the master branch as well.

```
future: <Task finished name='Task-542' coro=<WebsocketServer.serve() done, defined at /home/dmonad/utils/miniconda3/lib/python3.9/site-packages/ypy_websocket/websocket_server.py:97> exception=TypeError('can only concatenate list (not "bytes") to list')>
Traceback (most recent call last):
  File "/home/dmonad/utils/miniconda3/lib/python3.9/asyncio/tasks.py", line 256, in __step
    result = coro.send(None)
  File "/home/dmonad/utils/miniconda3/lib/python3.9/site-packages/ypy_websocket/websocket_server.py", line 100, in serve
    await sync(room.ydoc, websocket)
  File "/home/dmonad/utils/miniconda3/lib/python3.9/site-packages/ypy_websocket/ydoc.py", line 88, in sync
    msg = create_sync_step1_message(state)
  File "/home/dmonad/utils/miniconda3/lib/python3.9/site-packages/ypy_websocket/yutils.py", line 26, in create_sync_step1_message
    return create_message(data, YMessageType.SYNC_STEP1)
  File "/home/dmonad/utils/miniconda3/lib/python3.9/site-packages/ypy_websocket/yutils.py", line 22, in create_message
    return bytes([YMessageType.SYNC, msg_type] + write_var_uint(len(data)) + data)
TypeError: can only concatenate list (not "bytes") to list
```

Do you have an idea what this error means? I believe I'm running v0.1.9 (I checked `pip show ypy_websocket`).

**Comment by dmonad** [comment]
Got it, fixed it by specifying the latest ypy_websocket release in setup.cfg.
