### ISSUE TITLE
PanicException('called `Option::unwrap()` on a `None` value') 

### ISSUE THREAD

**Issue by chwzr** [y-crdt/ypy-websocket#51]
When using a yjs-websocket server ([https://github.com/yjs/y-websocket](https://github.com/yjs/y-websocket)) the ypy-websocket provider does not sync properly:

```
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/yrs-0.11.1/src/block.rs:1073:54

Traceback (most recent call last):
  File "/root/yspine-client/.venv/lib/python3.10/site-packages/ypy_websocket/websocket_provider.py", line 34, in _run
    await process_sync_message(message[1:], self._ydoc, self._websocket, self.log)
  File "/root/yspine-client/.venv/lib/python3.10/site-packages/ypy_websocket/yutils.py", line 130, in process_sync_message
    Y.apply_update(ydoc, update)
pyo3_runtime.PanicException: called `Option::unwrap()` on a `None` value

```
Other yjs clients on the same server work fine. 
Please let me know if you need further details or something to reproduce.

Cheers,
chwzr

**Comment by davidbrochart** [comment]
Thanks for reporting @chwzr, yes a reproducible example would help a lot.

**Comment by chwzr** [comment]
hi @davidbrochart  thanks for the quick reply!

here is a repo to reproduce the bug:

[https://github.com/chwzr/ypy-sync-issue](https://github.com/chwzr/ypy-sync-issue)

**Comment by davidbrochart** [comment]
Thanks a lot @chwzr, I could reproduce the issue.
It happens when the ypy client receives a `SYNC_STEP2` message from yjs, and could be linked to https://github.com/y-crdt/ypy/issues/94.
cc @dmonad @Horusiath @Waidhoferj
